import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // Main documentation sidebar with modules and chapters
  docsSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Module 1: Foundations of Robotics',
      collapsible: true,
      collapsed: false,
      items: [
        {type: 'autogenerated', dirName: 'module-01-foundations'},
      ],
      link: {
        type: 'doc',
        id: 'module-01-foundations/intro',
      },
    },
    {
      type: 'category',
      label: 'Module 2: Perception and Sensing',
      collapsible: true,
      collapsed: false,
      items: [
        {type: 'autogenerated', dirName: 'module-02-perception'},
      ],
      link: {
        type: 'doc',
        id: 'module-02-perception/intro',
      },
    },
    {
      type: 'category',
      label: 'Module 3: Control and Motion Planning',
      collapsible: true,
      collapsed: false,
      items: [
        {type: 'autogenerated', dirName: 'module-03-control'},
      ],
      link: {
        type: 'doc',
        id: 'module-03-control/intro',
      },
    },
    {
      type: 'category',
      label: 'Module 4: AI Agents in Robotics',
      collapsible: true,
      collapsed: false,
      items: [
        {type: 'autogenerated', dirName: 'module-04-ai-agents'},
      ],
      link: {
        type: 'doc',
        id: 'module-04-ai-agents/intro',
      },
    },
    {
      type: 'category',
      label: 'Module 5: Real-World Applications & Ethics',
      collapsible: true,
      collapsed: false,
      items: [
        {type: 'autogenerated', dirName: 'module-05-real-world'},
      ],
      link: {
        type: 'doc',
        id: 'module-05-real-world/intro',
      },
    },
  ],
};

export default sidebars;
